services:
  - type: web
    name: campusnest-website
    env: node
    repo: https://github.com/vibhorxpandey/campusnest-website
    branch: main
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    healthCheckPath: /api/health
    autoDeployTrigger: commit
